### ISSUE TITLE
run  example failed

### ISSUE THREAD

**Issue by BrokenWingsIcarus** [dreamlike-ocean/PanamaUring#2]
The. so file reports an error and cannot run on my host. Can you provide a c or cpp file? Let me compile it manually.

Connected to the target VM, address: '127.0.0.1:8381', transport: 'socket'
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\23630\AppData\Local\Temp\liburing10936049237759482352.so: %1 不是有效的 Win32 应用程序。
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2404)
	at java.base/java.lang.Runtime.load0(Runtime.java:785)
	at java.base/java.lang.System.load(System.java:2011)
	at top.dreamlike.async.uring.IOUring.<clinit>(IOUring.java:493)
	at top.dreamlike.async.uring.IOUringEventLoop.<init>(IOUringEventLoop.java:39)
	at iouring.FileOp.main(FileOp.java:17)
Disconnected from the target VM, address: '127.0.0.1:8381', transport: 'socket'

**Comment by dreamlike-ocean** [comment]
io_uring是linux专有的api
Windows上面请用IOCP的api 或者 使用内核版本在5.10以上的wsl2
我的wsl2内核版本是
Linux LAPTOP-970LJ1CQ 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by BrokenWingsIcarus** [comment]
我的问题， 忘记iouring的依赖问题了。

**Comment by dreamlike-ocean** [comment]
这个版本有个bug 待我修复一下。。。
